import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AmplifyConfigClientSide from './amplify/cognito.config'
const inter = Inter({ subsets: ['latin'] })
import { TRPCProvider } from '@/lib/providers/trpc.provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCProvider>
          <AmplifyConfigClientSide />
          {children}
        </TRPCProvider>
      </body>
    </html>
  )
}
