/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst'
export {}
declare module 'sst' {
  export interface Resource {
    AWS: {
      COGNITO_CLIENT_ID: string
      COGNITO_CLIENT_SECRET: string
      COGNITO_DOMAIN: string
      COGNITO_ISSUER: string
      COGNITO_POOL_ID: string
      type: 'sst.sst.Linkable'
    }
    GoogleClientId: {
      type: 'sst.sst.Secret'
      value: string
    }
    GoogleClientSecret: {
      type: 'sst.sst.Secret'
      value: string
    }
    NEXTAUTH_SECRET: {
      type: 'sst.sst.Secret'
      value: string
    }
    identityPool: {
      id: string
      type: 'sst.aws.CognitoIdentityPool'
    }
    userPool: {
      id: string
      type: 'sst.aws.CognitoUserPool'
    }
    web: {
      type: 'sst.aws.Nextjs'
      url: string
    }
    webClient: {
      id: string
      secret: string
      type: 'sst.aws.CognitoUserPoolClient'
    }
  }
}
